### PR TITLE
Add option to show release URL instead of opening it in the browser

### LINKED ISSUE #120: Add option for showing URL instead of opening the release in the default browser
My default browser is not the one I use for Github (long story). Opening the default browser is a nice default action but I'd (personally) like to alias `release` to `release -U` or something where `release` would instead just display the URL to navigate to directly in the CLI.

### PR DESCRIPTION
**Pull request by mcansh**
closes #120 
Signed-off-by: Logan McAnsh <logan@mcan.sh>

### CODE REVIEW

**Comment by leo** [comment]
Also: Thank you very much for this change!

**Comment by mcansh** [comment]
of course! should I use the default shortcut e.g. `-s` or do you have something else in mind?

**Comment by leo** [comment]
Thank you so much!

**Comment by Qix-** [comment]
Not sure how I missed this, but thanks!!

**Pull request merged**
