### PR TITLE
Move commit sha before commit message (#67)

### PR DESCRIPTION
**Pull request by onbjerg**
Reasoning in #67

### CODE REVIEW

**Comment by leo** [comment]
What about PRs and issues?

**Comment by onbjerg** [comment]
I'm not sure I follow. Did I miss something?

**Comment by leo** [comment]
@onbjerg This is how PRs and issues get linked: `#69` (no commit hash)

**Comment by dinoboff** [comment]
See line 14, the hash might be replaced with a PR/Issue number;  it wouldn't be aligned anymore.

https://github.com/zeit/release/pull/69/files#diff-8a7116152a042a7b35df8a2e18a96fd7R14

**Comment by onbjerg** [comment]
Oh. Damn. Not sure what to do about those, I'll try to think of something.

**Comment by citrusui** [comment]
Possibly, we could just detect if a message links to an available issue or PR via the API, and if so, construct a new Markdown header or two, e.g.:

## Closed Issues

#1: Resolved something zeit/release@c7d071ae

## Closed Pull Requests

#2: Resolved another zeit/release@c7d071ae

This could also be taken a step further, where `release` could fetch details on whether or not a commiter has previously contributed to project development. Example:

## Newest Collaborators

Thanks to @ghost, @ghost, and @ghost for their contributions!

...and if a person's Git email cannot be matched to a GitHub username, there should be a fallback to manual name or username entry.

**Comment by leo** [comment]
In the beginning, I already thought about putting the commit SHAs before the message. But as you can see, it won't really work out because there are many other format of the hash (could also be a issue or PR id). In turn, I'd like to keep it like it is!

**Pull request closed without merging**
